language: cpp

dist: trusty
sudo: false

os:
  - linux
  - osx

osx_image: xcode10.1

compiler:
  - clang
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
    fi;

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      if [ "$CXX" = "g++" ]; then
        export CXX=g++-7;
      fi;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      brew outdated gcc || brew upgrade gcc;
    fi;
env:
  global:
   - secure: "R+NxqtytOslIcQ/eCbLoZhImsgYdJnljfjANdieFQGune9ACPPQL0YanXkF49c9SWGBSxrAcute0egQzv2CU2+ivSQIX/xnMebKHiOmSPYBoxX+VgxLT3U1itUYlpYwixo9rF8UnGdlgXid6oENSiCvfWtNKoM2qOL0Ttw31J9E="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-7-dev
      - g++-7
      - libncursesw5-dev
  coverity_scan:
    project:
      name: "mawww/kakoune"
      description: "Build submitted via Travis CI"
    notification_email: frrrwww@gmail.com
    build_command_prepend: "cd src && make clean"
    build_command: "make -j4"
    branch_pattern: coverity-scan

script: cd src && make && make test
